---
title: "preliminaryTasks"
output: html_document
---

# Preliminary Task 1: Augmenting HTML to include header
```{r, message = F}
require(tidyverse)
require(tidytext)
require(textstem)
require(rvest)
require(qdapRegex)
require(stopwords)
require(tokenizers)
library(caret)
library(tidymodels)
```

## Updating Pre-processing Functions

Update `parse_fn` to include headers

```{r}
# function to parse html and clean text
parse_fn <- function(.html){
  read_html(.html) %>%
    html_elements('p, h1, h2, h3, h4, h5, h6') %>%
    html_text2() %>%
    str_c(collapse = ' ') %>%
    rm_url() %>%
    rm_email() %>%
    str_remove_all('\'') %>%
    str_replace_all(paste(c('\n', 
                            '[[:punct:]]', 
                            'nbsp', 
                            '[[:digit:]]', 
                            '[[:symbol:]]'),
                          collapse = '|'), ' ') %>%
    str_replace_all("([a-z])([A-Z])", "\\1 \\2") %>%
    tolower() %>%
    str_replace_all("\\s+", " ")
}

# function to apply to claims data
parse_data <- function(.df){
  out <- .df %>%
    filter(str_detect(text_tmp, '<!')) %>%
    rowwise() %>%
    mutate(text_clean = parse_fn(text_tmp)) %>%
    unnest(text_clean) 
  return(out)
}

nlp_fn <- function(parse_data.out){
  out <- parse_data.out %>% 
    unnest_tokens(output = token, 
                  input = text_clean, 
                  token = 'words',
                  stopwords = str_remove_all(stop_words$word, 
                                             '[[:punct:]]')) %>%
    mutate(token.lem = lemmatize_words(token)) %>%
    filter(str_length(token.lem) > 2) %>%
    count(.id, bclass, token.lem, name = 'n') %>%
    bind_tf_idf(term = token.lem, 
                document = .id,
                n = n) %>%
    pivot_wider(id_cols = c('.id', 'bclass'),
                names_from = 'token.lem',
                values_from = 'tf_idf',
                values_fill = 0)
  return(out)
}

# clean_df <- claims_test %>%
#   parse_data() %>%
#   select(.id, bclass, text_clean)
load('/Users/minu/Documents/GitHub/module-2-claims-data-table-12-1/data/claims-raw.RData')
claims_clean <- claims_raw %>%
  parse_data()
```

## Logistic PCR

```{r}
#text_features <- nlp_fn(claims_clean)
model_df <- text_features %>%
  select(-.id)

model_df$bclass <- as.factor(model_df$bclass)

set.seed(123)
split <- initial_split(model_df, strata = bclass)

train_df <- training(split)
test_df  <- testing(split)

pcr_recipe <- recipe(bclass ~ ., data = train_df) %>%
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors(), num_comp = 50)

logistic_spec <- logistic_reg(
  mode = "classification",
  penalty = 0.01,
  mixture = 0) %>%
  set_engine("glmnet")

pcr_wf <- workflow() %>%
  add_recipe(pcr_recipe) %>%
  add_model(logistic_spec)

final_fit <- fit(pcr_wf, train_df)

# Predictions (class)
pred_class <- predict(final_fit, test_df)

# Predictions (probabilities)
pred_prob <- predict(final_fit, test_df, type = "prob")

# Combine with test data
bclass <- as_tibble(test_df$bclass)
results <- bind_cols(bclass, pred_class, pred_prob) %>% 
  rename(bclass = value)

# Accuracy
accuracy(results, truth = bclass, estimate = .pred_class)
# 0.616
```


